### ISSUE TITLE
Python Dependency

### ISSUE THREAD

**Issue by bridgar** [Sonata-Princeton/SONATA-DEV#22]
There are some unlisted python package dependencies that reveal themselves when calling "vagrant up" or "vagrant provision"

![image](https://cloud.githubusercontent.com/assets/4304411/26532026/d71d55ba-43c4-11e7-9bb1-55dcbaa18d9c.png)

**Comment by robh2** [comment]
Are you referring to the SNIMissingWarning and InsecurePlatformWarning in the above screenshot?

**Comment by bridgar** [comment]
Outside of this, I have never seen the above SNIMissingWarning or InsecurePlatformWarning before. I know that they're just 'warnings' but they pop up several times during 'vagrant provision' and something is causing vagrant not to populate my VM properly. I don't have a ~/dev/examples folder in the VM.

**Comment by robh2** [comment]
Are you working off the latest in branch `master` ?

**Comment by bridgar** [comment]
Yes

**Comment by robh2** [comment]
Ok, if you're working off latest up-to-date branch `master` then you will not have a `~\dev\examples` folder.  The warnings do not actually affect the successful configuration of the VM.  Sounds like you should `vagrant destroy`, re-clone, and then try `vagrant up` again.

**Comment by bridgar** [comment]
I have destroyed, recloned, and rebuilt the vm. I still don't have a ~\dev\examples, though that seems to be consistent with what you're saying. Where should I find the examples to test from the README?

**Comment by robh2** [comment]
Ah, different problem.  The README is currently stale, which is bad form on our part, for branch `master`.  To close the loop on this thread, 1) the `SNIMissingWarning` and `InsecurePlatformWarning`s do not affect correct execution of the provisioning script.  They are an artifact of using an older version of python.  I am currently porting the provisioning scripts to an Ubuntu 16.04 platform to avoid these issues. 2) The current `README` has been updated to reflect the new path of where examples are now located but the remainder of the README may still contain inconsistencies.
