### ISSUE TITLE
Problems with Run query_engine.py script

### ISSUE THREAD

**Issue by Polly2014** [Sonata-Princeton/SONATA-DEV#37]
I'm a chinese student, and very intrested in sonata's view and idea. when I try to look over it's codes( the ```python sonata_queries.py``` in direcotry "/home/vagrant/dev/sonata/query_engine"), I met some problem:
```
vagrant@vighata:~/dev/sonata/query_engine$ python sonata_queries.py
Traceback (most recent call last):
  File "sonata_queries.py", line 409, in <module>
    q3.get_query_tree()
AttributeError: 'PacketStream' object has no attribute 'get_query_tree'
```
the two problem as below:
- there are no methods for PacketStream Object like get_query_tree(), get_all_queries(), get_partition_plans(), so can't use ```q3.get_query_tree()```
- when I import ```sonata.core.utils```, the get_query_tree(), get_all_queries() solved, but ```get_partition_plans()`` still not work
Hope you can give me some help, thanks

**Comment by agupta13** [comment]
@RohanBh will it be possible for you to take a quick look at this issue?

**Comment by RohanBh** [comment]
Hey @Polly2014! `get_partition_plans()` function was removed from the `PacketStream` class a long time ago. Now, there's a separate class for partitioning query which is [the Partition class][1] . There you can find `get_partition_plans()` function you're looking for.

[1]: https://github.com/Sonata-Princeton/SONATA-DEV/blob/de8d1b4713d3fca766a16c006eac5f91873ef0de/sonata/core/partition.py#L114

**Comment by Polly2014** [comment]
> Hey @Polly2014! `get_partition_plans()` function was removed from the `PacketStream` class a long time ago. Now, there's a separate class for partitioning query which is [the Partition class](https://github.com/Sonata-Princeton/SONATA-DEV/blob/de8d1b4713d3fca766a16c006eac5f91873ef0de/sonata/core/partition.py#L114) . There you can find `get_partition_plans()` function you're looking for.

Thanks, got it ^_^
